# docker exec -it lenslocked-db-1 /usr/bin/psql -U baloo -d lenslocked
# docker compose exec -it db psql -U baloo -d lenslocked
# host=localhost port=5432 user=baloo password=junglebook dbname=lenslocked sslmode=disable

# DEFINES THE DOCKER CONTAINER FOR BOTH DEVELOPMENT AND PRODUCTION ENVIRONMENTS

version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}