# docker exec -it lenslocked-db-1 /usr/bin/psql -U baloo -d lenslocked
# docker compose exec -it db psql -U baloo -d lenslocked
# host=localhost port=5432 user=baloo password=junglebook dbname=lenslocked sslmode=disable

# DEFINES THE DOCKER CONTAINER FOR DEVELOPMENT ENVIRONMENT ONLY
#
# Things that are already defined in `docker-compose.yml` do not have to be
# duplicated here.

version: "3.9"

services:
  # Our Postgres database
  db: # The service will be named db.
    ports: # Expose ports so that apps not running via docker-compose can connect to them.
      - 5432:5432 # format here is "port on our machine":"port on container"

  # Adminer provides a nice little web UI to connect to databases
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # Pick a theme - https://github.com/vrana/adminer/tree/master/designs
    ports:
      - 3333:8080