version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/lenslocked.wagnojunior.xyz/images:/app/images
    ports:
      - 3031:3031
    depends_on:
      - db
    networks:
      - caddy_caddy

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/lenslocked.wagnojunior.xyz/psql:/var/lib/postgresql/data/pgdata
    networks:
      - caddy_caddy

networks:
  caddy_caddy:
    external: true
