version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/lenslocked.wagnojunior.xyz/images:/app/images
    # ports: # TODO: DELETE PORTS WHEN RUNNING INSIDE A DOCKER CONTAINER
    #   - 3030:3030
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/lenslocked.wagnojunior.xyz/psql:/var/lib/postgresql/data/pgdata
